### ISSUE TITLE
Broken respawns

### ISSUE THREAD

**Issue by Centralan** [Centralan/Code4-CTF-Event#26]
## -- Respawning

local location = Location:new(myWorld, 44, 64, 0);

function blue_respawn(data)
         local targetPlayer = Player:new(data.player);
         if isPlayerOnBlueTeam(playerName) then
         targetPlayer:teleport(location);
    end
end

registerHook("PLAYER_DEATH", "blue_respawn", "Code4");

local location = Location:new(myWorld, -44, 64, 0);

function green_respawn(data)
         local targetPlayer = Player:new(data.player);
         if isPlayerOnGreenTeam(playerName) then
         targetPlayer:teleport(location);
    end
end

registerHook("PLAYER_DEATH", "green_respawn", "Code4");

This is not working as intended, instead of respawning at the points, it respawns in the lobby.

**Comment by Centralan** [comment]
@Kruithne

**Comment by Kruithne** [comment]
Well, it will do because the player is still dead so the game is going to respawn them at the world spawn point. You need to set their health back to 20, so they are no longer dead. I do predict that it might not actually stop the player from being teleported even after they are healed, if that be the case then we will need to wire in a PLAYER_DAMAGE event into the API so we can get them before they die.

Also, there's no need for two functions here as they use the same hook, we can merge them into one.

``` lua
local blueSpawnPoint = Location:new(world, 44, 64, 0);
local greenSpawnPoint = Location:new(world, -44, 64, 0);

function player_respawn(data)
    local targetPlayer = Player:new(data.player);

    if isPlayerOnBlueTeam(targetPlayer.name) then
        targetPlayer:teleport(blueSpawnPoint);
    elseif isPlayerOnGreenTeam(targetPlayer.name) then
        targetPlayer:teleport(greenSpawnPoint);
    end
end

registerHook("PLAYER_DEATH", "player_respawn", "Code4");
```

You were over-riding the locations with one another, so I've given them both unique names, `blueSpawnPoint` and `greenSpawnPoint`. You were also passing in `myWorld` but the script uses `world` all over the place, so we can just re-use that.

Another thing I noticed is you were passing `playerName` into `isPlayerOnBlueTeam` and `isPlayerOnGreenTeam` but I can't see anywhere that it's defined, so I changed it to `targetPlayer.name`.

**Comment by Centralan** [comment]
After adding this and set health it still is not working. Github Updated
